-- ============================================================
-- V1 · approval-service 初始 schema（审批流：approval_requests）
--
-- 设计依据：DATA_GOVERNANCE.md §4 数据建模 + ADR-0021/0025/0032
--   （业务服务独立迁移链 + tenant_id 逻辑引用无 DB FK）
-- ============================================================

CREATE TABLE approval_requests (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id    BIGINT         NOT NULL,
    type         VARCHAR(16)    NOT NULL,
    title        VARCHAR(128)   NOT NULL,
    amount       NUMERIC(14, 2),
    detail       VARCHAR(2000),
    requester_id BIGINT         NOT NULL,
    approver_id  BIGINT         NOT NULL,
    status       VARCHAR(16)    NOT NULL DEFAULT 'PENDING',
    comment      VARCHAR(500),
    decided_by   BIGINT,
    decided_at   TIMESTAMPTZ,
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ,
    CONSTRAINT ck_approval_requests_type CHECK (type IN ('EXPENSE', 'PURCHASE', 'SALE', 'OTHER')),
    CONSTRAINT ck_approval_requests_status CHECK (status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'))
);

CREATE INDEX idx_approval_requests_tenant ON approval_requests (tenant_id, created_at);
CREATE INDEX idx_approval_requests_tenant_status ON approval_requests (tenant_id, status);
CREATE INDEX idx_approval_requests_approver ON approval_requests (tenant_id, approver_id, status);
CREATE INDEX idx_approval_requests_requester ON approval_requests (tenant_id, requester_id);

COMMENT ON TABLE approval_requests IS '通用审批请求（审批流 · tenant_id 行级隔离 · ADR-0025/0032 模式）';
COMMENT ON COLUMN approval_requests.type IS 'EXPENSE 支出/报销 / PURCHASE 采购 / SALE 销售出库 / OTHER 其他';
COMMENT ON COLUMN approval_requests.title IS '审批标题（≤128）';
COMMENT ON COLUMN approval_requests.amount IS '金额（元，NUMERIC(14,2)，金额类单据填）';
COMMENT ON COLUMN approval_requests.detail IS '详情（JSON 文本或自由描述，≤2000）';
COMMENT ON COLUMN approval_requests.requester_id IS '发起人（逻辑 ref -> users.id，来自 X-User-Id）';
COMMENT ON COLUMN approval_requests.approver_id IS '指定审批人（逻辑 ref -> users.id）';
COMMENT ON COLUMN approval_requests.status IS 'PENDING 待审批 / APPROVED 已通过 / REJECTED 已驳回 / CANCELLED 已撤销（终态不可再流转）';
COMMENT ON COLUMN approval_requests.comment IS '审批意见（驳回必填）/ 撤销原因';
COMMENT ON COLUMN approval_requests.decided_by IS '决策人（审批人 或 撤销的发起人）';
COMMENT ON COLUMN approval_requests.decided_at IS '决策时间';
