-- ============================================================
-- V2 · 审批操作审计（ADR-0032 阶段 2 · DATA_SECURITY §7 append-only）
-- 表名 approval_audit_logs：全局唯一（ADR-0031 教训：共享 public schema
-- 表名必须唯一，user 用 audit_logs、crm 用 customer_audit_logs）
-- ============================================================

CREATE TABLE approval_audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT         NOT NULL,
    action      VARCHAR(32)    NOT NULL,        -- CREATE / APPROVE / REJECT / CANCEL
    resource_id BIGINT,                          -- approval_requests.id
    actor_id    BIGINT,                          -- 操作人（X-User-Id）
    outcome     VARCHAR(16)    NOT NULL,         -- SUCCESS / FAILURE
    detail      VARCHAR(1000),
    source_ip   VARCHAR(64),
    user_agent  VARCHAR(512),
    request_id  VARCHAR(64),
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_approval_audit_tenant
    ON approval_audit_logs (tenant_id, created_at);
CREATE INDEX idx_approval_audit_resource
    ON approval_audit_logs (resource_id);
