-- ============================================================
-- V12 · 站内通知（framework-domain Notification 实体）
-- 实体：cn.huntercat.lieshou.framework.domain.Notification
-- 表名 notifications：全局唯一（ADR-0031：共享 public schema 表名必须唯一）
-- tenant_id + user_id 定位接收者（租户隔离）；read_at 为空 = 未读；
-- biz_type / biz_id 预留业务关联（审批/审计等扩展）
-- ============================================================

CREATE TABLE notifications (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id   BIGINT         NOT NULL,
    user_id     BIGINT         NOT NULL,
    type        VARCHAR(16)    NOT NULL DEFAULT 'SYSTEM', -- SYSTEM / APPROVAL / AUDIT
    title       VARCHAR(255)   NOT NULL,
    content     TEXT,
    biz_type    VARCHAR(64),                               -- 预留业务关联类型
    biz_id      BIGINT,                                    -- 预留业务关联 ID
    read_at     TIMESTAMPTZ,                               -- NULL = 未读
    created_at  TIMESTAMPTZ    NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_recipient
    ON notifications (tenant_id, user_id, read_at);
CREATE INDEX idx_notifications_biz
    ON notifications (biz_type, biz_id);
